## PYTHON
#### Öğrendiklerimizin tekrarı ve ek toparlayıcı bilgiler.

## Yapılandırılmış Veri : NumPy in yapılandırılmış Verileri

In [1]:
import numpy as np
rand = np.random.RandomState(42)

In [2]:
ad = ['Ayşe', 'Ali', 'Veli', 'Fatma']
yas = [25, 45, 37, 19]
kilo = [55.0, 85.5, 68.0, 61.5]

In [3]:
x = np.zeros(4, dtype=int)

In [4]:
# Yapısal diziler için birleşik veri tipleri kullanma
data = np.zeros(4, dtype={'names':('ad', 'yas', 'kilo'),
                          'formats':('U10', 'i4', 'f8')})
print(data.dtype)

[('ad', '<U10'), ('yas', '<i4'), ('kilo', '<f8')]


In [5]:
data['ad'] = ad
data['yas'] = yas
data['kilo'] = kilo
print(data)

[('Ayşe', 25, 55. ) ('Ali', 45, 85.5) ('Veli', 37, 68. )
 ('Fatma', 19, 61.5)]


In [6]:
# İsim listesini alalım
data['ad']

array(['Ayşe', 'Ali', 'Veli', 'Fatma'], dtype='<U10')

In [7]:
# Verinin 1.satırı
data[0]

('Ayşe', 25, 55.)

In [8]:
# Son satırdaki ad bilgisi
data[-1]['ad']

'Fatma'

In [9]:
data['yas'] < 30 

array([ True, False, False,  True])

In [10]:
data[   data['yas'] < 30    ]

array([('Ayşe', 25, 55. ), ('Fatma', 19, 61.5)],
      dtype=[('ad', '<U10'), ('yas', '<i4'), ('kilo', '<f8')])

In [11]:
# Yaşı 30 un altındaki kişilerin adları. 
data[   data['yas'] < 30    ]['ad']

array(['Ayşe', 'Fatma'], dtype='<U10')

In [ ]:
## Yapılandırılmış dizileri oluşturma

In [12]:
np.dtype({'names':('ad', 'yas', 'kilo'),
          'formats':('U10', 'i4', 'f8')})

dtype([('ad', '<U10'), ('yas', '<i4'), ('kilo', '<f8')])

In [13]:
np.dtype({'names':('ad', 'yas', 'kilo'),
          'formats':((np.str_, 10), int, np.float32)})

dtype([('ad', '<U10'), ('yas', '<i8'), ('kilo', '<f4')])

In [14]:
np.dtype([('ad', 'S10'), ('yas', 'i4'), ('kilo', 'f8')])

dtype([('ad', 'S10'), ('yas', '<i4'), ('kilo', '<f8')])

In [15]:
np.dtype('S10,i4,f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

In [16]:
# Daha da ileri düzey Birleşik tipldr

In [17]:
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])
X = np.zeros(1, dtype=tp)
print(X[0])
print(X['mat'][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
data['yas']

array([25, 45, 37, 19], dtype=int32)

In [20]:
data_rec = data.view(np.recarray)
data_rec.yas

array([25, 45, 37, 19], dtype=int32)

In [21]:
%timeit data['yas']
%timeit data_rec['yas']
%timeit data_rec.yas

174 ns ± 11.2 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
2.59 µs ± 29.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
3.25 µs ± 185 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [22]:
## Pandas ile veri manipulasyonu

In [23]:
## Pandas Kütüphanesi

In [24]:
import pandas
pandas.__version__

'0.25.1'

In [25]:
import pandas as pd

In [27]:
##pd.<TAB> ile pandasın içeriğini öğrenebilirirz. inceleyebilirsiniz.


## Pandas Serisi Objeleri

In [28]:
import numpy as np
import pandas as pd

In [29]:
## Pandas Serisi indeksli bir boyutlu dizidir. Bir listeden ve diziden oluşturulabilinir.
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [31]:
type(data)

pandas.core.series.Series

In [33]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [34]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [35]:
data[1]

0.5

In [36]:
data[1:3]

1    0.50
2    0.75
dtype: float64

## NumPy diziden oluşturulmuş gibi Seriler

In [38]:
data = pd.Series(      [0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [39]:
data['b']

0.5

In [40]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [41]:
data[5]

0.5

## Özelleştirilmiş sözlük olarak Seriler

In [42]:
nufus_sozluk = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
nufus = pd.Series(nufus_sozluk)
nufus

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [43]:
nufus['California']

38332521

In [44]:
nufus['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

## Series objeleri oluşturma

In [45]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [46]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [47]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [48]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

## Pandas Data Frame Objesi

## NumPy dizisinden oluşturulan  Data Frame

In [49]:
alan_sozluk = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
alan = pd.Series(alan_sozluk)
alan

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [50]:
eyaletler = pd.DataFrame({'nufus': nufus,
                       'alan': alan})
eyaletler

nufus    alan
California  38332521  423967
Texas       26448193  695662
New York    19651127  141297
Florida     19552860  170312
Illinois    12882135  149995

In [51]:
eyaletler.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [53]:
eyaletler.columns

Index(['nufus', 'alan'], dtype='object')

## Özelleştirilmiş sözlük olarak Data Frameler

In [54]:
eyaletler['alan']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: alan, dtype: int64

## Data Frame objeleri oluşturma

In [57]:
pd.DataFrame(nufus, columns=['nufus'])

nufus
California  38332521
Texas       26448193
New York    19651127
Florida     19552860
Illinois    12882135

In [58]:
data = [{'a': i, 'b': 2 * i}
        for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [59]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [60]:
pd.DataFrame(np.random.rand(3, 2),
             columns=['yiyecek', 'içecek'],
             index=['a', 'b', 'c'])

yiyecek    içecek
a  0.690329  0.491700
b  0.804749  0.848595
c  0.854076  0.961420

In [61]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [62]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0