## PYTHON
#### Öğrendiklerimizin tekrarı ve ek toparlayıcı bilgiler.

## Toplama

In [1]:
import numpy as np
## 1 den 6 ya kadar sayıların toplamı
x = np.arange(1, 6)
np.add.reduce(x)
## 1 2 3 4 5   
## 1 2 6 24 120


15

In [2]:
np.multiply.reduce(x)

120

In [3]:
## kumulatıf almak
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [4]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

## En küçük  en büyük ve Toplama

## Dizilerdeki Değerleri Toplamak

In [5]:
L = np.random.random(100)
sum(L)

47.89780792922389

In [6]:
np.sum(L)

47.89780792922389

In [7]:
big_array = np.random.rand(100000)
%timeit sum(big_array)
%timeit np.sum(big_array)

14 ms ± 612 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
27.8 µs ± 275 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [8]:
M = np.random.random((3, 4))
print(M)

[[0.72966057 0.08096524 0.4464086  0.22593947]
 [0.51354202 0.39681746 0.75730945 0.1876984 ]
 [0.30606632 0.19212899 0.01749943 0.99520244]]


In [9]:
M.sum()

4.849238379792896

## Dizilerde en küçük  ve en büyük değerler

In [10]:
min(big_array), max(big_array)

(3.516450999163645e-06, 0.9999964713617848)

In [11]:
np.min(big_array), np.max(big_array)

(3.516450999163645e-06, 0.9999964713617848)

In [12]:
%timeit min(big_array)
%timeit np.min(big_array)

8.08 ms ± 191 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
33.1 µs ± 305 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [13]:
print(big_array.min(), big_array.max(), big_array.sum())

3.516450999163645e-06 0.9999964713617848 49892.909552639765


In [14]:
M.min(axis=0)

array([0.30606632, 0.08096524, 0.01749943, 0.1876984 ])

In [15]:
M.max(axis=1)

array([0.72966057, 0.75730945, 0.99520244])

### Fonksiyon Adı 	NaN-güvenli Versiyon	Açıklaması
### np.sum      	np.nansum           	Elemanların toplamı
### np.prod     	np.nanprod          	Elemanların Çarpımı
### np.mean     	np.nanmean          	Elemanların ortalaması
### np.std      	np.nanstd           	Elemanların standart sapması
### np.var      	np.nanvar           	Elemanların varyansı
### np.min      	np.nanmin           	Elemanların en küçüğü
### np.max       	np.nanmax           	Elemanların en büyüğü
### np.argmin   	np.nanargmin        	Elemanların en küçüğünün endeksi
### np.argmax   	np.nanargmax        	Elemanların en büyüğünün endeksi
### np.median   	np.nanmedian        	Elemanların medyanı
### np.percentile  	np.nanpercentile    	Elemanların rank bazlı istatistiği
### np.any      	N/A	herhangi bir elemanı doğrumu
### np.all      	N/A	tüm elemanları doğrumu

In [16]:
## Örnek : Amerikan Başkanlarının boy ortalaması

In [17]:
!head -4 data/president_heights.csv

order,name,height(cm)
1,George Washington,189
2,John Adams,170
3,Thomas Jefferson,189


In [18]:
import pandas as pd
data = pd.read_csv('data/president_heights.csv')
data.head(3)

order               name  height(cm)
0      1  George Washington         189
1      2         John Adams         170
2      3   Thomas Jefferson         189

In [19]:
heights = np.array(data['height(cm)'])
print(heights)

[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 168 170 178 182 180 183 178 182 188 175 179 183 193 182 183
 177 185 188 188 182 185]


In [20]:
print("Ortalama boy       :", heights.mean())
print("Standart sapma     :", heights.std())
print("En kısa boy        :", heights.min())
print("En uzun boy        :", heights.max())

Ortalama boy       : 179.73809523809524
Standart sapma     : 6.931843442745892
En kısa boy        : 163
En uzun boy        : 193


In [21]:
print("%25 lik. kısım   :", np.percentile(heights, 25))
print("ORrtanca         :", np.median(heights))
print("%75 lik. kısım   :", np.percentile(heights, 75))

%25 lik. kısım   : 174.25
ORrtanca         : 182.0
%75 lik. kısım   : 183.0


## Diziler ile yapılan işlemler

In [22]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [23]:
a + 5

array([5, 6, 7])

In [24]:
M = np.ones(  (3, 3)  )
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [26]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [27]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

## Diziler ile yapılan işlemlerde uyulması gerekli kurallar ve örnekli Anlatım

In [28]:
## Örnek 1

In [29]:
M = np.ones((2, 3))
a = np.arange(3)

In [30]:
##Dizlerin Şekillerini öğrenelim
M.shape = (2, 3)
a.shape = (3,)
print (M)
print (a)
print (M.shape)
print (a.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
(2, 3)
(3,)


In [31]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [32]:
## Örnek 2

In [33]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)

In [34]:
print ('a =',a)
print ('b =',b)
print ('a nin şekli =',a.shape)
print ('b nin şekli =',b.shape)


a = [[0]
 [1]
 [2]]
b = [0 1 2]
a nin şekli = (3, 1)
b nin şekli = (3,)


In [35]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

## Örnek 3

In [36]:
M = np.ones((3, 2))
a = np.arange(3)

In [37]:
a[:, np.newaxis].shape

(3, 1)

In [38]:
M + a[:, np.newaxis]

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

In [39]:
np.logaddexp(M, a[:, np.newaxis])

array([[1.31326169, 1.31326169],
       [1.69314718, 1.69314718],
       [2.31326169, 2.31326169]])

In [40]:
## Fantezi endeksleme

In [41]:
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [42]:
[x[3], x[7], x[2]]

[71, 86, 14]

In [43]:
listem = [3, 7, 2]
x[listem]

array([71, 86, 14])

In [44]:
listem = np.array([   [3, 7],  [4, 5]   ])
x[listem]

array([[71, 86],
       [60, 20]])

In [45]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

array([ 2,  5, 11])

In [47]:
X[row[:, np.newaxis], col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

In [48]:
row[:, np.newaxis] * col

array([[0, 0, 0],
       [2, 1, 3],
       [4, 2, 6]])

In [49]:
## Birleştirilmiş endeksleme

In [50]:
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [51]:
X[2, [2, 0, 1]]

array([10,  8,  9])

In [52]:
X[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

In [53]:
mask = np.array([1, 0, 1, 0], dtype=bool)
X[row[:, np.newaxis], mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [54]:
## Fantezi endeksleme ile verileri değiştirme

In [55]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


In [56]:
x[i] -= 10
print(x)

[ 0 89 89  3 89  5  6  7 89  9]


In [57]:
x = np.zeros(10)
x[[0, 0]] = [4, 6]
print(x)

[6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [58]:
i = [2, 3, 3, 4, 4, 4]
x[i] += 1
x

array([6., 0., 1., 1., 1., 0., 0., 0., 0., 0.])

In [59]:
x = np.zeros(10)
np.add.at(x, i, 1)
print(x)

[0. 0. 1. 2. 3. 0. 0. 0. 0. 0.]


## Sıralama işlemleri

In [60]:
import numpy as np

def selection_sort(x):
    for i in range(len(x)):
        swap = i + np.argmin(x[i:])
        (x[i], x[swap]) = (x[swap], x[i])
    return x

In [61]:
x = np.array([2, 1, 4, 3, 5])
selection_sort(x)

array([1, 2, 3, 4, 5])

In [62]:
def bogosort(x):
    while np.any(x[:-1] > x[1:]):
        np.random.shuffle(x)
    return x

In [63]:
x = np.array([2, 1, 4, 3, 5])
bogosort(x)

array([1, 2, 3, 4, 5])

## NumPy de hızlı sorgulama np.sort and np.argsort

In [64]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [65]:
x.sort()
print(x)

[1 2 3 4 5]


In [66]:
## Sıralamayı indeks numaralarına göre alır.
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

[1 0 3 2 4]


In [67]:
x[i]

array([1, 2, 3, 4, 5])

## satırlar ve sütunlar üzerinde sıralama

In [68]:

rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [69]:
# sort each column of X
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [70]:
# sort each row of X
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

## Parçalı sıralama

In [71]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])

In [72]:
np.partition(X, 2, axis=1)

array([[3, 4, 6, 7, 6, 9],
       [2, 3, 4, 7, 6, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 9, 5]])