## PYTHON
#### Öğrendiklerimizin tekrarı ve ek toparlayıcı bilgiler.

In [1]:
## Önce Pythonda yardım almayı öğrenelim
print('Öğrenmek istediğimiz komutu help metoduyla öğreniriz')
help(print)

Öğrenmek istediğimiz komutu help metoduyla öğreniriz
Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [2]:
## yada daha hızlı bir şekilde komut ve ? işareti
print?

In [3]:
## kullanmayı öğrendikce sizi öok daha detaylı bilgiler veriyor olacak 
## bu yüzden fonksiyon yazar iken bizde yardım dokumanını hazırlamamız lazım. Kullanıcılarımıza destek olmak için 
L = [1, 2, 3]
L.insert?

In [4]:
L?

In [5]:
def karesi(a):
    """ a sayısının karesini alır."""
    return a ** 2

In [6]:
karesi?

In [7]:
## Kaynak koda ulaşmak için ?? karakterlerini kullanacağız

In [8]:
karesi??

In [9]:
print??

In [10]:
## Modullerde tab isaretinin kullanımı.
## Lütfen L. yazdıktan sonra tab tuşuna basarmısnız

In [11]:
## Gördüğünüz bu liste bir liste oluşturduğunuzda hangi metodları kullanabildiğinizi gösteriyor
## L.append   L.copy     L.extend   L.insert   L.remove   L.sort     
## L.clear    L.count    L.index    L.pop      L.reverse  
## listeye ekle, kopyala, uzat, araya ekle, sil, sırala, temizle, say, indeks, sil ve göster, 
## ters çevir gibi metodlar. 

In [12]:
##L.c ve tab tuşuna bastığınızda ise sadece L.copy ve L.count metodları belirecektir.

In [13]:
## tab tuşuna o kelime ile ilgili metodları bilmediğimiz her. yerde kullanırız
## örneğin 
## from itertools import co<TAB> deneyiniz lütfen 


In [14]:
## içinde Warning kelimesi geçiyorsa göster
## *Warning?
*Warning?

In [15]:
str.*find*?

In [16]:
## gönderdiğimiz satır komutlarının işlenme sürelerine ihtiyacımız oldugunda %timeit 
## komutun başına yazdığımızda bu komutun işlenme süresi hakkında bilgi alırız.
%timeit L = [n ** 2 for n in range(1000)]

325 µs ± 82 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [17]:
%%timeit
L = []
for n in range(1000):
    L.append(n ** 2)

388 µs ± 37.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [18]:
%magic

In [19]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%

In [20]:
## Önce IN ve OUTu öğreneceğiz demiştik
a=2
a

2

In [21]:
## alttaki satırları çalıştıralım
import math

In [22]:
math.sin(2)

0.9092974268256817

In [23]:
math.cos(2)

-0.4161468365471424

In [24]:
print(In)

['', "## Önce Pythonda yardım almayı öğrenelim\nprint('Öğrenmek istediğimiz komutu help metoduyla öğreniriz')\nhelp(print)", "## yada daha hızlı bir şekilde komut ve ? işareti\nget_ipython().run_line_magic('pinfo', 'print')", "## kullanmayı öğrendikce sizi öok daha detaylı bilgiler veriyor olacak \n## bu yüzden fonksiyon yazar iken bizde yardım dokumanını hazırlamamız lazım. Kullanıcılarımıza destek olmak için \nL = [1, 2, 3]\nget_ipython().run_line_magic('pinfo', 'L.insert')", "get_ipython().run_line_magic('pinfo', 'L')", 'def karesi(a):\n    """ a sayısının karesini alır."""\n    return a ** 2', "get_ipython().run_line_magic('pinfo', 'karesi')", '## Kaynak koda ulaşmak için ?? karakterlerini kullanacağız', "get_ipython().run_line_magic('pinfo2', 'karesi')", "get_ipython().run_line_magic('pinfo2', 'print')", '## Modullerde tab isaretinin kullanımı.\n## Lütfen L. yazdıktan sonra tab tuşuna basarmısnız', '## Gördüğünüz bu liste bir liste oluşturduğunuzda hangi metodları kullanabildiğini

In [25]:
Out

{19: Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pyp

In [26]:
print(In[1])

## Önce Pythonda yardım almayı öğrenelim
print('Öğrenmek istediğimiz komutu help metoduyla öğreniriz')
help(print)


In [27]:
## İlk Kütüphanemiz NUMPY ve versiyonu

In [28]:
import numpy
numpy.__version__

'1.17.2'

In [29]:
## Kütüphaneşeri okunuş kolaylıkları için kısaltma tercih edilen bir yöntemdir.
import numpy as np

In [30]:
np?

In [31]:
## np.<TAB> lütfen deneyiniz

In [32]:
## c# kod örneği 
## int result = 0;
## for(int i=0; i<100; i++){
##    result += i;
##}

In [33]:
##  # Python code
##  result = 0
##  for i in range(100):
##     result += i

In [34]:
## Python kodlarının daha sade olduğunu biliyoruz

### Veri Tipi 	Açıklaması
### bool_	Mantıksal  (Doğru yada Yanlış) byte olarak saklanır
### int_	  Öndeğer Tamsayı tipi  (C long gibi ; normal olarak ya int64 yada int32)
### intc	  C tamsayısının aynısıdır (normal olarak  int32 yada int64)
### intp	  Endeksleme kullanılam tamsayı  (C deki gibi ; normal olarak ya int32 yada int64)
### int8      Bayt (-128 to 127)
### int16	 Tamsayı (-32768 to 32767)
### int32	 Tamsayı (-2147483648 den 2147483647 e)
### int64    Tamsayı (-9223372036854775808 den 9223372036854775807 e)
### uint8	 Pozitif Tamsayı (0 to 255)
### uint16	Pozitif Tamsayı (0 to 65535)
### uint32	Pozitif Tamsayı (0 to 4294967295)
### uint64	Pozitif Tamsayı (0 to 18446744073709551615)
### float_   float64 ın kısaltılmışı
### float16	Yarı hassas gerçek sayı:   işaret  bit, 5 bitlik üs, 10 bitlik mantis
### float32	hassas gerçek sayı:  işaret  bit, 8 bitlik üs, 23 bitlik mantis
### float64	çift hassas gerçek sayı:  işaret  bit, 11 bitlik üs, 52 bitlik mantis
### complex_	   complex128 kısaltılmışı
### complex64	  Kompleks Sayı  2adet  32-bit gerçek sayı ile sunulur
### complex128	 Kompleks Sayı  2adet  64-bit gerçek sayı ile sunulur

In [35]:
## Basit Numpy Dizileri

In [36]:
import numpy as np
# Hep aynı rastgele seçilen sayılar ile işlem yapmak ister isek
np.random.seed(0)  
## Bir boyutlu dizi
x1 = np.random.randint(10, size=6)   
## İki boyutlu dizi
x2 = np.random.randint(10, size=(3, 4))  
## Üç boyutlud izi
x3 = np.random.randint(10, size=(3, 4, 5))  

In [37]:
print("x3 kaç boyutlu: ", x3.ndim)
print("x3 şekli:", x3.shape)
print("x3 büyüklüğü: ", x3.size)

x3 kaç boyutlu:  3
x3 şekli: (3, 4, 5)
x3 büyüklüğü:  60


In [38]:
print("data tipi : ", x3.dtype)

data tipi :  int64


In [39]:
print("Büyüklüğü:", x3.itemsize, "bytes")
print("Boyutu :", x3.nbytes, "bytes")

Büyüklüğü: 8 bytes
Boyutu : 480 bytes


In [40]:
x1

array([5, 0, 3, 3, 7, 9])

In [41]:
x1[1]

0

In [42]:
x1[-1]

9

In [43]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [44]:
x2[0, 0]

3

In [45]:
x2[2, -1]

7

In [46]:
x2[0, 0] = 12

In [47]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [48]:
## Dizilerde Parça al
## x[başlangıç noktası:son nokta:aralık]


In [49]:
# Bir boyutlu dizilerde parça al
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [50]:
x[:6] 

array([0, 1, 2, 3, 4, 5])

In [51]:
x[6:] 

array([ 6,  7,  8,  9, 10, 11])

In [52]:
x[5:9] 

array([5, 6, 7, 8])

In [53]:
x[::2]

array([ 0,  2,  4,  6,  8, 10])

In [54]:
x[1::2] 

array([ 1,  3,  5,  7,  9, 11])

In [55]:
x[::-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [56]:
x[5::-2]

array([5, 3, 1])

In [57]:
# İki boyutlu dizilerde parça al
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [58]:
x2[:2, :3] 

array([[12,  5,  2],
       [ 7,  6,  8]])

In [59]:
x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [60]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [61]:
print(x2[:, 0]) 

[12  7  1]


In [62]:
print(x2[0, :])

[12  5  2  4]


In [63]:
print(x2[0])  # not  x2[0, :] 

[12  5  2  4]


In [64]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [65]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [66]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [67]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [68]:
## dizi kopyalama
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [69]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [70]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
