### Bilimsel hesaplarda kullanılan Python Veri Bilimcilerin Kütüphanesi 'numpy'

#### Numpy vektor ve matriksler gibi yüksek performanslı çok boyutlu işlem yeteneği sağlar

In [1]:
## numpy kütüphanesini yükleyelim
import numpy as np

In [2]:
Listem=[1,2,3,4,5,6,7,8,9,10,11,12]
print (Listem)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


In [3]:
type(Listem)

list

In [4]:
numpy_listem = list(range(1, 13))
print (numpy_listem)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


In [5]:
numpy_listem = list(range(1, 13,2))
print (numpy_listem)

[1, 3, 5, 7, 9, 11]


In [6]:
## np.array diziye çevirir
dizim = np.array(Listem)

In [7]:
dizim

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
type(dizim)

numpy.ndarray

In [9]:
np.square(dizim)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [10]:
Matriksim = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [11]:
Matriksim

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [12]:
Matriksim_dizi_hali=np.array(Matriksim)

In [13]:
Matriksim_dizi_hali

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
## dizimiz kaç satır kaç kolondan oluşur 
Matriksim_dizi_hali.shape

(4, 3)

In [15]:
#i# ster isek kaç satır var diye sorarız
Matriksim_dizi_hali.shape[0]

4

In [16]:
#i# ster isek kaç sütun var diye sorarız
Matriksim_dizi_hali.shape[1]

3

In [17]:
## dizideki tüm elemanların karekökünü alabiliriz
np.sqrt(Matriksim_dizi_hali)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162]])

In [18]:
## dizideki tüm elemanların logaritmasını alabiliriz
np.log(Matriksim_dizi_hali)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458],
       [2.30258509, 2.39789527, 2.48490665]])

In [19]:
## şimdi biraz ha ilerliyelim
Parametremiz0 = np.zeros((3, 4))

In [20]:
Parametremiz0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
Parametremiz1 = np.ones((4, 3))

In [22]:
Parametremiz1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
## Rasgele 4 tane sayı üretelim
rasgele_4_sayı = np.random.rand(4)
rasgele_4_sayı

array([0.63863089, 0.61483455, 0.73253282, 0.33938915])

In [24]:
## Rasgele 4 satır 5 sütun bir dizi üretelim
rasgele_1_dizi = np.random.randn(4, 3)
rasgele_1_dizi

array([[ 0.6578445 , -0.38202967,  1.51115579],
       [-0.37809704,  1.48717462, -1.15580115],
       [-0.02110325, -0.02593962, -0.36974728],
       [ 2.01091691, -0.64247497,  0.60600557]])

In [25]:
## rasgele 1 ile 100 arasında bir tamsayı çağıralım
np.random.randint(1, 100)

89

In [26]:
## rasgele 1 ile 100 arasında 5 tamsayı çağıralım
np.random.randint(1, 100, 5)

array([52, 25, 41,  4, 85])

In [27]:
## rasgele 1 ile 15 arasında 4 sayı çağıralım ama bu sayilar arasindaki mesafe esit olsun
np.linspace(1, 15, 4)

array([ 1.        ,  5.66666667, 10.33333333, 15.        ])

In [28]:
14/3

4.666666666666667

In [29]:
1+14/3

5.666666666666667

In [30]:
1+14/3+14/3

10.333333333333334

In [31]:
1+14/3+14/3+14/3

15.0

In [32]:
## Birim matrix oluşturma
birim_matriks=np.eye(5)
birim_matriks

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
## 5 satır 5 sutunlu bir matriks oluşturalım
matriks1 = np.random.rand(5, 5)

In [34]:
matriks1

array([[0.26204443, 0.03144718, 0.47848999, 0.64144255, 0.39468013],
       [0.16118528, 0.39043862, 0.06904922, 0.29786836, 0.35893446],
       [0.40578722, 0.15002469, 0.37438037, 0.18368843, 0.73438624],
       [0.07464715, 0.42901599, 0.74723492, 0.38078626, 0.03549908],
       [0.37622503, 0.43625351, 0.51748453, 0.71024943, 0.64515861]])

In [35]:
## bir matriks ile birim matriksin çarpımı np.dot()
matriks_carpimi = np.dot(birim_matriks, matriks1)

In [36]:
matriks_carpimi

array([[0.26204443, 0.03144718, 0.47848999, 0.64144255, 0.39468013],
       [0.16118528, 0.39043862, 0.06904922, 0.29786836, 0.35893446],
       [0.40578722, 0.15002469, 0.37438037, 0.18368843, 0.73438624],
       [0.07464715, 0.42901599, 0.74723492, 0.38078626, 0.03549908],
       [0.37622503, 0.43625351, 0.51748453, 0.71024943, 0.64515861]])

In [37]:
## eleman yntemiyle dizi çarpım işlemi ise
matriks_carpimi = np.multiply(birim_matriks, matriks1)

In [38]:
matriks_carpimi

array([[0.26204443, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.39043862, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.37438037, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.38078626, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.64515861]])

In [39]:
matriks1.shape

(5, 5)

In [40]:
matriks_satir = matriks1.reshape(25, 1)

In [41]:
matriks_satir

array([[0.26204443],
       [0.03144718],
       [0.47848999],
       [0.64144255],
       [0.39468013],
       [0.16118528],
       [0.39043862],
       [0.06904922],
       [0.29786836],
       [0.35893446],
       [0.40578722],
       [0.15002469],
       [0.37438037],
       [0.18368843],
       [0.73438624],
       [0.07464715],
       [0.42901599],
       [0.74723492],
       [0.38078626],
       [0.03549908],
       [0.37622503],
       [0.43625351],
       [0.51748453],
       [0.71024943],
       [0.64515861]])

In [42]:
matriks_satir.shape

(25, 1)

In [43]:
matriks_satir[0:5]

array([[0.26204443],
       [0.03144718],
       [0.47848999],
       [0.64144255],
       [0.39468013]])

In [44]:
matriks_satir[0:5]=3

In [45]:
matriks_satir

array([[3.        ],
       [3.        ],
       [3.        ],
       [3.        ],
       [3.        ],
       [0.16118528],
       [0.39043862],
       [0.06904922],
       [0.29786836],
       [0.35893446],
       [0.40578722],
       [0.15002469],
       [0.37438037],
       [0.18368843],
       [0.73438624],
       [0.07464715],
       [0.42901599],
       [0.74723492],
       [0.38078626],
       [0.03549908],
       [0.37622503],
       [0.43625351],
       [0.51748453],
       [0.71024943],
       [0.64515861]])

In [46]:
matriks_satir.ndim

2

In [47]:
matriks_satir_parca = matriks_satir[0:3]

In [48]:
matriks_satir_parca

array([[3.],
       [3.],
       [3.]])

In [49]:
matriks_satir_parca[:] = 6

In [50]:
matriks_satir_parca

array([[6.],
       [6.],
       [6.]])

In [51]:
matriks_sütun = matriks1.reshape(1,25)

In [52]:
matriks_sütun

array([[6.        , 6.        , 6.        , 3.        , 3.        ,
        0.16118528, 0.39043862, 0.06904922, 0.29786836, 0.35893446,
        0.40578722, 0.15002469, 0.37438037, 0.18368843, 0.73438624,
        0.07464715, 0.42901599, 0.74723492, 0.38078626, 0.03549908,
        0.37622503, 0.43625351, 0.51748453, 0.71024943, 0.64515861]])

In [53]:
matriks_sütun.ndim

2

In [54]:
len(matriks_sütun)

1

In [55]:
matriks_sütun.shape

(1, 25)